### ISSUE TITLE
some flaw in Array addition 

### ISSUE THREAD

**Issue by SaddamBInSyed** [AnoshaRehan/Coding-Challenges#1]
https://github.com/AnoshaRehan/Coding-Challenges/blob/621442a431d77b2ef6710aaeacd83142e8d09193/arrayAddition.py#L23

why not we can do like below?

def ArrayAdditionI_Fast(arr):
    arr = sorted(arr)
    print(arr)
    max_value = arr[-1]
    **arr = arr[:-1]**
    print(arr)
    arr = arr[:1]
    print(arr)
    total = 0
    for i in arr:
        total = total + i
    return 'True' if total == max_value else 'False'

**Comment by AnoshaRehan** [comment]
Hi. The problem with your approach is that it will always add *all *numbers
excluding the maximum one and the question states that *any *combination
added up to equal the maximum number. So for example for an array input [5,
2, 3, 1, 7] , 7 is maximum and 5+2=7 so function should return *true, *however
your function would compare 5+2+3+1 (11==7) which is false and incorrect.
Hope that clears things up.

**Comment by AnoshaRehan** [comment]
Hi. The problem with your approach is that it will always add **all** numbers excluding the maximum one and the question states that **any** combination added up to equal the maximum number. So for example for an array input `[5, 2, 3, 1, 7]` , 7 is maximum and 5+2=7 so function should return `true`, however your `for loop` would end up comparing 5+2+3+1 (11==7) which is `false` and incorrect.
Hope that clears things up.

**Comment by SaddamBInSyed** [comment]
@AnoshaRehan 

Thank you for your comment. Yes, I didn't notice that ANY word...

by the way, I am going to take the Coderbyte challenge (Python) soon, If you any advice let me know here. ( 2+ years exp)

thanks once again

**Comment by AnoshaRehan** [comment]
Sorry but I haven't attempted that challenge yet but I wish you the best!
